import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/NavbarDemo";
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import { Suspense } from "react";
import { ServiceCTA } from "@/components/services/ServiceCTA";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <Suspense>
            <Navigation />
            {children}
            <ServiceCTA />
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
